### SignUp
POST http://localhost:3000/api/v1/users/signup
Content-Type: application/json

{
  "name": "admin",
  "email": "admin@gmail.com",
  "password": "12345678",
  "passwordConfirm": "12345678",
  "role": "admin"
}

### LogIn
POST http://localhost:3000/api/v1/users/login
Content-Type: application/json

{
  "email": "leo@gmail.com",
  "password": "12345678"
}

> {% client.global.set('token',response.body.token) %}

### ForgotPassword
POST http://localhost:3000/api/v1/users/forgot-password
Content-Type: application/json

{
  "email": "ale@gmail.com"
}

### ResetPassword
PATCH http://localhost:3000/api/v1/users/reset-password/5c8980ec3c6d68601dcb668bffe7df7cbcfa179bfe1e6a000fc18a83f6e920f8
Content-Type: application/json

{
  "password": "asdfasdf",
  "passwordConfirm": "asdfasdf"
}

### UpdatePassword
PATCH http://localhost:3000/api/v1/users/update-password
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "oldPassword": "asdfasdf",
  "newPassword": "12345678",
  "newPasswordConfirm": "12345678"
}

### UpdateMe
PATCH http://localhost:3000/api/v1/users/update-me
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "ale",
  "email": "ale@gmail.com",
  "role": "admin"
}

### DeleteMe
DELETE http://localhost:3000/api/v1/users/delete-me
Content-Type: application/json
Authorization: Bearer {{token}}

### GetAllUsers
GET http://localhost:3000/api/v1/users
Accept: application/json

###
